UPDATE subcategory SET
  Pic = 'india_family.jpg',
  Detail = 'India is a land of incredible diversity — from the snow-capped peaks of the Himalayas and the golden sands of Rajasthan to the lush backwaters of Kerala and the ancient temples of Tamil Nadu. A family holiday to India is a sensory adventure like no other. Watch your children''s eyes widen at the majesty of the Taj Mahal at sunrise, explore the magnificent forts and palaces of Jaipur, cruise through the serene backwaters of Alleppey, and experience the colourful chaos of a traditional Indian bazaar. India offers world-class wildlife safaris in Ranthambore and Corbett, thrilling rickshaw rides through Old Delhi, cooking classes, elephant encounters, and so much more. Our carefully curated family packages handle every detail — comfortable hotels, private guides, seamless transportation, and age-appropriate activities — so you can focus entirely on making lifelong memories together. Whether your family seeks history, adventure, wildlife, or spiritual discovery, India delivers it all in breathtaking abundance.'
WHERE Subcatid = 1;

UPDATE subcategory SET
  Pic = 'canada_family.jpg',
  Detail = 'Canada is the ultimate playground for adventurous families. Stretching across vast wilderness from the Atlantic to the Pacific, this magnificent country offers some of the world''s most spectacular natural wonders. Discover the impossibly turquoise waters of Lake Louise and Moraine Lake in the Canadian Rockies, spot grizzly bears and wolves in Banff National Park, and ride through dramatic mountain passes on the legendary Rocky Mountaineer train. From the thundering power of Niagara Falls to the vibrant, multicultural energy of Vancouver and Toronto, Canada captivates at every turn. Our family adventure packages include white water rafting on the Kicking Horse River, guided glacier walks on the Columbia Icefields, kayaking expeditions, stargazing nights under the northern lights, and authentic ranch experiences. Canada''s wide open spaces, pristine air, and warm local hospitality create the perfect environment for families to reconnect, explore, and discover the extraordinary together. An adventure your children will talk about for decades.'
WHERE Subcatid = 2;

UPDATE subcategory SET
  Pic = 'italy_family.jpg',
  Detail = 'Italy is an open-air museum, a culinary paradise, and a land of extraordinary natural beauty — making it one of the world''s most captivating destinations for a family holiday. Walk through 2,000 years of history in Rome, tossing coins into the Trevi Fountain and exploring the awe-inspiring Colosseum. Marvel at Michelangelo''s David in Florence and glide along Venice''s magical canals in a traditional gondola. Discover the dramatic coastline of the Amalfi Coast with its colourful cliffside villages tumbling into the sparkling Mediterranean sea. Hike the ancient paths of Cinque Terre, visit the preserved ruins of Pompeii at the foot of Mount Vesuvius, and taste freshly made gelato and pizza in the piazzas of Naples. Our Italy family holidays are crafted to balance world-class cultural exploration with relaxed beach time, ensuring children and adults are equally enchanted. Italy''s warmth, passion, and extraordinary food make every moment of this family holiday a genuine celebration of la dolce vita — the sweet life.'
WHERE Subcatid = 3;

UPDATE subcategory SET
  Pic = 'religious_india.jpg',
  Detail = 'India is one of the world''s most sacred lands — the birthplace of four great religions (Hinduism, Buddhism, Jainism, and Sikhism) and home to thousands of temples, mosques, churches, and shrines of profound spiritual significance. A religious tour of India is a deeply moving and transformative journey for the soul. Stand in awe before the Golden Temple in Amritsar as its radiant reflection shimmers in the sacred Sarovar lake at dawn. Witness the mesmerising Ganga Aarti ceremony on the ancient ghats of Varanasi as hundreds of oil lamps drift down the sacred Ganges river. Embark on the arduous but deeply rewarding Char Dham Yatra through the majestic Himalayas. Trace the footsteps of Lord Buddha from Bodh Gaya to Sarnath to Kushinagar. Bow before the towering gopurams of the magnificent Meenakshi Amman Temple in Madurai and the brilliantly carved Brihadeeswarar Temple in Thanjavur. From the desert temples of Rajasthan to the pilgrimage sites of Vrindavan, Mathura, Tirupati, and Shirdi — India''s spiritual tapestry is boundless, deeply personal, and absolutely unforgettable. Let us guide you on a journey that nourishes both the spirit and the soul.'
WHERE Subcatid = 4;
